name = "Minecraft Work Space Mod Packs"
author = "Mellr1s"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "212f0ef425cf37740af0249fc591b1f3d27f047cfb75d87e4c5409e33fba28fa"

[versions]
fabric = "0.19.5"
minecraft = "1.21.11"
