name = "Minecraft Work Space Mod Packs"
author = "Mellr1s"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "97707b9ef0f7cfb2aa175a36dc31cd207c5f52be72d515637811f7318778415b"

[versions]
fabric = "0.19.5"
minecraft = "1.21.11"
