name = "Minecraft Work Space Mod Packs"
author = "Mellr1s"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "233210aba2c24a612e2c6ad00111316a54a082d7602030e82253361740b7e81b"

[versions]
fabric = "0.19.5"
minecraft = "1.21.11"
